manager:
  tokenFormat: "%s%s%s%s%s%s%s%s%s%s%s-%s%s%s%s%s%s%s%s%s%s%s-%s%s%s%s%s%s%s%s%s%s"
  
  receiveTimeout: 30000
  
jms:
   provider: RABBIT_MQ
   
   hostName: "35.240.82.108"
   
   automaticRecovery: true
   
   durable: true
   
   exclusive: false
   
   autoDelete: false
   
   timeout: 30000
   
   timeoutTimeUnit: TimeUnit.SECONDS