spring:
   data:
      mongodb:
         host: 35.240.82.108
         port: 27017
         authentication-database: admin
         username: user
         password: user
         database: app_log

manager:
  tokenFormat: "%s%s%s%s%s%s%s%s%s%s%s-%s%s%s%s%s%s%s%s%s%s%s-%s%s%s%s%s%s%s%s%s%s"
  receiveTimeout: 30000
 
jms:
   provider: RABBIT_MQ
   
   
   rabbitmq:
      hostName: 35.240.82.108
      port: 5672
      automaticRecovery: true
      
      userName: test
      password: test
      
      config:
         dlqExchangePrefix: dlq
         durable: true
         exclusive: false
         autoDelete: true
         receiveTimeout: 30000
         receiveTimeoutTimeUnit: SECONDS
         messageTTL: 1000